### ISSUE TITLE
version 20200215 named 20180927 in the assets ?

### ISSUE THREAD

**Issue by mherrb** [hboetes/mg#17]
Hi,

The source  tarball and ZIP archives for the 20200215 release are 
https://github.com/hboetes/mg/archive/20180927.zip and https://github.com/hboetes/mg/archive/20180927.tar.gz 
that's a bit confusing...

**Comment by liangfu** [comment]
It's actually release in 20180927.

For 20200215 release, they are
https://github.com/hboetes/mg/archive/20200215.zip and 
https://github.com/hboetes/mg/archive/20200215.tar.gz

**Comment by hboetes** [comment]
Hello Matthieu,

I'm afraid I can't reproduce your issue either. It all looks like it should be. Is there anything you can add to clarify why you are running into this issue?

Thanks

**Comment by mherrb** [comment]
Hi,
you're both right. I didn't look closely enough, perhaps because the way github is presenting things confused my (the 20180927 release files are presented with a larger font, and the fact that the title for this release doesn't include the version name itself. Anyways, issue closed. Thanks for your help!
