### ISSUE TITLE
Upon saving, file permissions are restored to the value they had when file was opened

### ISSUE THREAD

**Issue by grothesque** [hboetes/mg#20]
Here is a demonstration of the problem, using mg 20200723-1 as packaged in Debian testing:

```
% mg foo
# Edit buffer, save it, suspend mg.
zsh: suspended  mg foo
% chmod 600 foo
% fg
[2]  - continued  mg foo
# Modify buffer, save it again, suspend mg.
zsh: suspended  mg foo
% ls -l foo
-rw-rw-r-- 1 user user 9 Jan  5 17:24 foo
```

This behavior can be a problem if one edits configuration files that need specific permissions.  This is how I got bitten by it.

Other editors I checked (GNU emacs and zile) preserve permissions that are modified while a file is open.

**Comment by hboetes** [comment]
I'm terribly sorry, but I only maintain the port. The upstream code is managed by the OpenBSD team. Please report your problem over there. tech@openbsd.org is the proper mailing list.
