### ISSUE TITLE
Backspace Key not deleting

### ISSUE THREAD

**Issue by yamunan-bitset** [hboetes/mg#23]
Hello, as I read in the tutorial file, it said ```To delete characters, use the backspace key.``` But when I did backspace, it showed ```a b c:```. I am not sure if this has a different meaning, but it would be useful to have a backspace working rather than moving one letter forward and doing ^D.
Thanks

**Comment by hboetes** [comment]
Your terminal is sending ^H instead of ^?, this is not a bug with mg, but a misconfiguration of your terminal.

**Comment by harridu** [comment]
Actually ^H (aka "BS") is the correct setting for the Backspace key. But its not in wide use, so emacs reused ^H for help.
