### ISSUE TITLE
Which mg does Apple ship?

### ISSUE THREAD

**Issue by frou** [hboetes/mg#24]
Hi there - I notice that Apple is now shipping `mg` (whether it's part of the base MacOS install, or part of their optional "Command Line Tools for Xcode" package, I'm not sure, as I've already installed the latter on my machine).

I'm wondering which `mg` codebase they're using, and went looking at https://opensource.apple.com , but could not find any trace of mg.

Do you know what the deal is?

**Comment by hboetes** [comment]
I have no idea nor any means to find it out. I also don't see how this question has any relevance to this little project.
