### ISSUE TITLE
Requesting support for Parinfer

### ISSUE THREAD

**Issue by kathe** [hboetes/mg#26]
I don't know who the original maintainers of "mg" (under OpenBSD) are, so writing to you with the hope that either you could consider providing the requested feature, or forward this request to the appropriate individual(s).

Would it be possible for "mg" to provide parentheses balancing and indentation support using the Parinfer mechanism/algorithm?
Description of Parinfer is available at https://shaunlebron.github.io/parinfer/
Hope I haven't overstepped my limits by requesting the above. Thank you.

**Comment by hboetes** [comment]
I'm terribly sorry, but mg is intended as a minimal editor, and I just maintain porting the application.

This sounds like a great feature for Emacs. And a Google search reveals:

  https://github.com/DogLooksGood/parinfer-mode

**Comment by kathe** [comment]
> I'm terribly sorry, but mg is intended as a minimal editor, and I just maintain porting the application.

No worries. Yes, I knew that you only maintain the port. And, yes, I know that "mg" is intended as a minimal editor, but having parentheses balancing with indentation support for Lisp wouldn't add too much code while making "mg" feature complete as far as Lisp support goes.

May I know who to contact regarding pleading my case with? I would prefer a one-on-one conversation rather than a full-out mailing list exchange which usually leads to crass comments culminating in an all out war.  :-)

> This sounds like a great feature for Emacs. And a Google search reveals:
> https://github.com/DogLooksGood/parinfer-mode

Parinfer is just the algorithm, it has been implemented in Emacs Lisp, JavaScript, VimScript and few other languages, hence there's no reason why it cannot be implemented in ANSI-C for "mg".
