### ISSUE TITLE
Feature request: kill-whole-line

### ISSUE THREAD

**Issue by Piscium** [hboetes/mg#28]
In other editors I often kill a whole line, for example, using dd in vi. It would be nice to be able to do that in mg.

How it is done in emacs (kill-whole-line):
https://www.gnu.org/software/emacs/manual/html_node/emacs/Killing-by-Lines.html

**Comment by hboetes** [comment]
I just maintain the port, so I import all changes from OpenBSD mg:
https://cvsweb.openbsd.org/src/usr.bin/mg/?sortby=date#dirlist

So your best course of action is to send them a feature request, or even better, to send them a patch. Once it has been implemented you can ask me to sync with the upstream repo, and I'll do that ASAP.
