### ISSUE TITLE
Three more bugs in display-wide-characters

### ISSUE THREAD

**Issue by mazocomp** [hboetes/mg#3]
Hi!

First, I noticed auto-fill-mode bug: one UTF-8 character counts as multiple characters. That is, it creates new line too early.

Second, just right after that I tried to delete characters at next line. When I delete that line, the last character at previous line is also removed.

**Comment by mazocomp** [comment]
Third, typing only alphanumeric characters at multiple lines counts as one word and when I remove that word with M-Backspace, I get some charactes after cursor.

**Comment by s-gilles** [comment]
Should be fixed, I think.

-- 
S. Gilles

**Comment by mazocomp** [comment]
@s-gilles Yep, they are fixed.
