### ISSUE TITLE
indent mode does not respect set-tab-width

### ISSUE THREAD

**Issue by uselpa** [hboetes/mg#31]
Hello
when using the following configuration, both on Debian, macOS and Alpine Linux
```
backup-to-home-directory
set-tab-width 4
set-default-mode indent
```
indenting once works well, but when I indent a line twice, pressing <return> sets the cursor back to the first indent:
```
aaa
aaa
    sss
        sddd
    cursor here after return, should be indented 1 level further
```
Bug or user error?
Regards
-Patrick

**Comment by hboetes** [comment]
I have no idea, I only ported mg, I don't know all the ins and outs of the program. For questions like that, please refer to the documentation or the openbsd-misc mailing list.

**Comment by mpwillson** [comment]
This appears to be a defect in mg; a hard-coded tab width of 8 in util.c (doindent). I've sumbitted a patch to bugs@openbsd.org.

**Comment by uselpa** [comment]
> This appears to be a defect in mg; a hard-coded tab width of 8 in util.c (doindent). I've sumbitted a patch to [bugs@openbsd.org](mailto:bugs@openbsd.org).

Thank you so much.
Yesterday I installed OpenBSD just to check whether the behaviour was the same there. It was.
I looks like I might be the only mg user not using the standard value of 8.
I actually found another bug but I will investigate then once this one is fixed.
KUDOS for (1) suggesting a patch (2) to an OpenBSD mailing list :)

**Comment by hboetes** [comment]
> This appears to be a defect in mg; a hard-coded tab width of 8 in util.c (doindent). I've sumbitted a patch to [bugs@openbsd.org](mailto:bugs@openbsd.org).
You can easily check the latest commits here:
http://cvsweb.openbsd.org/cgi-bin/cvsweb/src/usr.bin/mg/?sortby=date#dirlist
If you see an update there, just reply in this thread and I'll apply it. As a matter of fact, there's an update I haven't commited yet.

**Comment by mpwillson** [comment]
Omar Polo has committed a slightly modified patch to fix this issue in util.c 1.51. Should apply without a problem, I trust.

**Comment by hboetes** [comment]
Thanks for the heads-up, the CVS mirror I'm using is lagging.
